---
- name: 'Shared YML chunks'
  meta: noop
  args:
    minecraft_owned: &mco
      owner: "{{ minecraft_user }}"
      group: "{{ minecraft_group }}"

- name: 'Dynmap config'
  copy:
    <<: *mco
    src: files/dynmap_configuration.yml
    dest: "{{ plugin_dir }}/dynmap/configuration.txt"
  notify:
    - restart minecraft
- name: 'Dynmap webroot'
  file:
    <<: *mco
    path: "{{ minecraft_map_webroot }}"
    state: directory

- name: 'Install Lighttpd'
  apt:
    name: lighttpd
- name: 'Allow http in'
  ufw:
    rule: allow
    port: http
- name: 'Allow https in'
  ufw:
    rule: allow
    port: https
- name: 'Lighttpd config'
  template:
    src: templates/lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
  notify:
    - restart lighttpd

- name: 'Install certbot'
  apt:
    name: certbot

- name: 'Check if certificate exists'
  stat:
    path: "/etc/letsencrypt/live/{{ ansible_fqdn }}/cert.pem"
  register: cert_exists
- name: 'Stop lighttpd for certbot'
  service:
    name: lighttpd
    state: stopped
  when: not cert_exists.stat.exists
- name: 'Get initial certificate'
  command:
    cmd: >
      certbot certonly -n -m {{ admin_email }} --agree-tos
      --standalone -d {{ ansible_fqdn }}
  when: not cert_exists.stat.exists
- name: 'Combined key/cert file'
  assemble:
    remote_src: yes
    src: "/etc/letsencrypt/live/{{ ansible_fqdn }}"
    regexp: "(privkey|cert)\\.pem"
    dest: "/etc/letsencrypt/live/{{ ansible_fqdn }}/combined.pem"
  when: not cert_exists.stat.exists
- name: 'Allow webserver to read live cert'
  file:
    path: /etc/letsencrypt/live
    group: www-data
    mode: 'g+x'
  when: not cert_exists.stat.exists
- name: 'Allow webserver to read archive cert'
  file:
    path: /etc/letsencrypt/archive
    group: www-data
    mode: 'g+x'
  when: not cert_exists.stat.exists
- name: 'Start lighttpd for certbot'
  service:
    name: lighttpd
    state: started
  when: not cert_exists.stat.exists

- name: 'Letsencrypt deploy hook'
  template:
    src: templates/certbot_renew_deploy_hook.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/lighttpd.sh
    mode: '0700'
