---
- name: 'Enable Firewall'
  ufw:
    state: enabled
- name: 'Allow outgoing'
  ufw:
    default: allow
    direction: outgoing
- name: 'Allow SSH'
  ufw:
    rule: allow
    port: ssh
- name: 'Deny incomming'
  ufw:
    default: deny
    direction: incoming
- name: 'Local timezone'
  timezone:
    name: "{{ time_zone }}"
- name: 'Mincraft group'
  group:
    name: "{{ minecraft_group }}"
    system: yes
- name: 'Minecraft user'
  user:
    name: "{{ minecraft_user }}"
    system: yes
    create_home: yes
    home: "{{ minecraft_dir }}"
    group: "{{ minecraft_group }}"
- name: 'Minecraft directory'
  file:
    path: "{{ minecraft_dir }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755
