---
- name: 'Install build reqs'
  apt:
    pkg:
      - git
      - build-essential
- name: 'Get installed mcrcon version'
  command: 'mcrcon -v'
  ignore_errors: yes
  changed_when: no
  register: mcrcon_installed_version
- name: 'Force install mcrcon if wrong version'
  set_fact:
    mcrcon_reinstall_from_source: yes
  when: >
    mcrcon_installed_version is succeeded and
    ( mcrcon_installed_version.stdout_lines[0] |
      regex_replace("^[^ ]* ([0-9]+\.[0-9]+\.[0-9]+) .*$", "\\1" )
      is version(mcrcon_version, "<") )
- name: 'Get mcrcon source'
  git:
    repo: 'https://github.com/Tiiffi/mcrcon.git'
    dest: /usr/local/src/mcrcon
    version: "v{{ mcrcon_version }}"
- name: 'Build mcrcon'
  make:
    chdir: /usr/local/src/mcrcon
  when: 'mcrcon_installed_version is failed or mcrcon_reinstall_from_source'
- name: 'Install mcrcon'
  make:
    chdir: /usr/local/src/mcrcon
    target: install 
  when: 'mcrcon_installed_version is failed or mcrcon_reinstall_from_source'
