---
- name: 'Shared YML chunks'
  meta: noop
  args:
    minecraft_owned: &mco
      owner: "{{ minecraft_user }}"
      group: "{{ minecraft_group }}"
    restart_minecraft: &rst
      notify:
        - restart minecraft

- name: 'Install Java'
  apt:
    name: openjdk-8-jre-headless
- name: 'Download Paper jar'
  get_url:
    <<: *mco
    url: "https://papermc.io/api/v1/paper/{{ paper_version }}/{{ paper_build }}/download"
    dest: "{{ minecraft_dir }}/server/paper-{{ paper_build }}.jar"
    backup: yes
- name: 'Link to Paper download'
  <<: *rst
  file:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/paper.jar"
    src: "{{ minecraft_dir }}/server/paper-{{ paper_build }}.jar"
    state: link
    follow: no
- name: 'Agree to EULA'
  copy:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/eula.txt"
    content: "eula=true\n"
- name: 'Server properties'
  <<: *rst
  template:
    <<: *mco
    src: templates/server.properties.j2
    dest: "{{ minecraft_dir }}/server/server.properties"
- name: 'Bukkit config'
  <<: *rst
  copy:
    <<: *mco
    src: files/bukkit.yml
    dest: "{{ minecraft_dir }}/server/bukkit.yml"
- name: 'Spigot config'
  <<: *rst
  copy:
    <<: *mco
    src: files/spigot.yml
    dest: "{{ minecraft_dir }}/server/spigot.yml"
- name: 'Paper config'
  <<: *rst
  copy:
    <<: *mco
    src: files/paper.yml
    dest: "{{ minecraft_dir }}/server/paper.yml"
- name: 'User whitelist'
  <<: *rst
  copy:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/whitelist.json"
    content: "{{ user_whitelist }}"
- name: 'Minecraft systemd unit'
  template:
    src: templates/minecraft.service.j2
    dest: /etc/systemd/system/minecraft@.service
- name: 'Minecraft service'
  systemd:
    name: 'minecraft@server.service'
    enabled: yes
    state: started
    daemon_reload: yes
- name: 'Allow Minecraft in firewall'
  ufw:
    rule: allow
    port: "{{ minecraft_port }}"
