---
- name: 'Install Java'
  apt:
    name: openjdk-8-jre-headless
- name: 'Download Paper jar'
  get_url:
    url: "https://papermc.io/api/v1/paper/{{ paper_version }}/{{ paper_build }}/download"
    dest: "{{ minecraft_dir }}/server/paper-{{ paper_build }}.jar"
    backup: yes
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
- name: 'Link to Paper download'
  file:
    dest: "{{ minecraft_dir }}/server/paper.jar"
    src: "{{ minecraft_dir }}/server/paper-{{ paper_build }}.jar"
    state: link
    follow: no
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
- name: 'Agree to EULA'
  copy:
    dest: "{{ minecraft_dir }}/server/eula.txt"
    content: "eula=true\n"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
- name: 'Server properties'
  template:
    src: templates/server.properties.j2
    dest: "{{ minecraft_dir }}/server/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
- name: 'Bukkit config'
  copy:
    src: files/bukkit.yml
    dest: "{{ minecraft_dir }}/server/bukkit.yml"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
- name: 'Spigot config'
  copy:
    src: files/spigot.yml
    dest: "{{ minecraft_dir }}/server/spigot.yml"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
- name: 'Paper config'
  copy:
    src: files/paper.yml
    dest: "{{ minecraft_dir }}/server/paper.yml"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
- name: 'User whitelist'
  copy:
    dest: "{{ minecraft_dir }}/server/whitelist.json"
    content: "{{ user_whitelist }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
- name: 'Minecraft systemd unit'
  template:
    src: templates/minecraft.service.j2
    dest: /etc/systemd/system/minecraft@.service
- name: 'Minecraft service'
  systemd:
    name: 'minecraft@server.service'
    enabled: yes
    state: started
    daemon_reload: yes
- name: 'Allow Minecraft in firewall'
  ufw:
    rule: allow
    port: "{{ minecraft_port }}"
