---
- name: 'Shared YML chunks'
  meta: noop
  args:
    minecraft_owned: &mco
      owner: "{{ minecraft_user }}"
      group: "{{ minecraft_group }}"
    restart_minecraft: &rst
      notify:
        - restart minecraft

- name: 'Allow Minecraft in firewall'
  ufw:
    rule: allow
    port: "{{ minecraft_port }}"
- name: 'Install Java'
  apt:
    name: openjdk-17-jre-headless
- name: 'Server directory'
  file:
    <<: *mco
    path: "{{ minecraft_dir }}/server"
    state: directory
- name: 'Paper version information'
  uri:
    url: "https://papermc.io/api/v2/projects/paper/versions/{{ paper_version }}"
    return_content: yes
  register: 'paper_ver_response'
- name: 'Set paper build number'
  set_fact:
    paper_build: "{{ paper_ver_response.json.builds[-1] }}"
- name: 'Paper build information'
  uri:
    url: "https://papermc.io/api/v2/projects/paper/versions/{{ paper_version }}/builds/{{ paper_build }}"
    return_content: yes
  register: 'paper_build_response'
- name: 'Set Paper download name'
  set_fact:
    paper_download: "{{ paper_build_response.json.downloads.application.name }}"
- name: 'Download Paper jar'
  get_url:
    <<: *mco
    url: "https://papermc.io/api/v2/projects/paper/versions/{{ paper_version }}/builds/{{ paper_build }}/downloads/{{ paper_download }}"
    dest: "{{ minecraft_dir }}/server/{{ paper_download }}"
    backup: yes
- name: 'Link to Paper download'
  <<: *rst
  file:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/paper.jar"
    src: "{{ minecraft_dir }}/server/{{ paper_download }}"
    state: link
    follow: no
- name: 'Agree to EULA'
  copy:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/eula.txt"
    content: "eula=true\n"
- name: 'Server properties'
  <<: *rst
  template:
    <<: *mco
    src: templates/server.properties.j2
    dest: "{{ minecraft_dir }}/server/server.properties"
- name: 'Minecraft systemd unit'
  template:
    src: templates/minecraft.service.j2
    dest: /etc/systemd/system/minecraft@.service
- name: 'Minecraft service'
  systemd:
    name: 'minecraft@server.service'
    enabled: yes
    state: started
    daemon_reload: yes
- name: 'Bukkit config'
  <<: *rst
  copy:
    <<: *mco
    src: files/bukkit.yml
    dest: "{{ minecraft_dir }}/server/bukkit.yml"
- name: 'Spigot config'
  <<: *rst
  copy:
    <<: *mco
    src: files/spigot.yml
    dest: "{{ minecraft_dir }}/server/spigot.yml"
- name: 'Paper config'
  <<: *rst
  copy:
    <<: *mco
    src: files/paper.yml
    dest: "{{ minecraft_dir }}/server/paper.yml"
- name: 'User whitelist'
  <<: *rst
  copy:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/whitelist.json"
    content: "{{ minecraft_users | json_query('[*].{ name: name, uuid: uuid }') }}"
