---
- name: 'Install plugins'
  copy:
    src: "files/plugins/{{ item.file }}"
    dest: "{{ minecraft_dir }}/server/plugins/{{ item.file }}"
    checksum: "{{ item.checksum }}"
    backup: yes
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
  loop: "{{ bukkit_plugins }}"

- name: 'Cenotaph config'
  copy:
    src: files/cenotaph_config.yml
    dest: "{{ minecraft_dir }}/server/plugins/Cenotaph/config.yml"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - restart minecraft
