---
- name: 'Shared YML chunks'
  meta: noop
  args:
    minecraft_owned: &mco
      owner: "{{ minecraft_user }}"
      group: "{{ minecraft_group }}"
    restart_minecraft: &rst
      notify:
        - restart minecraft

- name: 'Install plugins'
  <<: *rst
  copy:
    <<: *mco
    src: "files/plugins/{{ item.file }}"
    dest: "{{ plugin_dir }}/{{ item.file }}"
    checksum: "{{ item.checksum }}"
    backup: yes
  loop: "{{ bukkit_plugins }}"

- name: 'Cenotaph config'
  <<: *rst
  copy:
    <<: *mco
    src: files/cenotaph_config.yml
    dest: "{{ plugin_dir }}/Cenotaph/config.yml"
- name: 'LuckPerms config'
  <<: *rst
  copy:
    <<: *mco
    src: files/luckperms_config.yml
    dest: "{{ plugin_dir }}/LuckPerms/config.yml"
