- name: 'Mincraft group'
  group:
    name: "{{ minecraft_group }}"
    system: yes
- name: 'Minecraft user'
  user:
    name: "{{ minecraft_user }}"
    system: yes
    create_home: yes
    home: "{{ minecraft_dir }}"
    group: "{{ minecraft_group }}"
- name: 'Minecraft directory'
  file:
    path: "{{ minecraft_dir }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755

- name: 'Allow Minecraft in firewall'
  ufw:
    rule: allow
    port: "{{ minecraft_port }}"
- name: 'Install Java'
  apt:
    name: openjdk-21-jre-headless

- include_tasks: server.yml
