---
- name: 'Shared YML chunks'
  meta: noop
  args:
    minecraft_owned: &mco
      owner: "{{ minecraft_user }}"
      group: "{{ minecraft_group }}"
    restart_minecraft: &rst
      notify:
        - restart minecraft

- name: 'Paper version information'
  uri:
    url: "https://papermc.io/api/v2/projects/paper/versions/{{ paper_version }}"
    return_content: yes
  register: 'paper_ver_response'
- name: 'Set paper build number'
  set_fact:
    paper_build: "{{ paper_ver_response.json.builds[-1] }}"
- name: 'Paper build information'
  uri:
    url: "https://papermc.io/api/v2/projects/paper/versions/{{ paper_version }}/builds/{{ paper_build }}"
    return_content: yes
  register: 'paper_build_response'
- name: 'Set Paper download name'
  set_fact:
    paper_download: "{{ paper_build_response.json.downloads.application.name }}"
- name: 'Download Paper jar'
  get_url:
    <<: *mco
    url: "https://papermc.io/api/v2/projects/paper/versions/{{ paper_version }}/builds/{{ paper_build }}/downloads/{{ paper_download }}"
    dest: "{{ minecraft_dir }}/server/{{ paper_download }}"
    backup: yes
- name: 'Link to Paper download'
  <<: *rst
  file:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/paper.jar"
    src: "{{ minecraft_dir }}/server/{{ paper_download }}"
    state: link
    follow: no
