---
- name: 'Shared YML chunks'
  meta: noop
  args:
    minecraft_owned: &mco
      owner: "{{ minecraft_user }}"
      group: "{{ minecraft_group }}"
    restart_minecraft: &rst
      notify:
        - restart minecraft

- name: 'User whitelist'
  <<: *rst
  copy:
    <<: *mco
    dest: "{{ minecraft_dir }}/server/whitelist.json"
    content: "{{ minecraft_users | json_query('[*].{ name: name, uuid: uuid }') }}"

- name: 'LuckPerms config'
  <<: *rst
  copy:
    <<: *mco
    src: luckperms_config.yml
    dest: "{{ plugin_dir }}/LuckPerms/config.yml"

- name: 'LuckPerms permission dir'
  file:
    <<: *mco
    path: "{{ perm_dir }}"
    state: directory

- name: 'Allow syncing'
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^%sudo'
    line: "{{ lookup('env', 'USER') }} ALL=NOPASSWD: /usr/bin/rsync"
    validate: '/usr/sbin/visudo -cf %s'

- name: 'Group permissions'
  <<: *rst
  synchronize:
    src: groups/
    dest: "{{ perm_dir }}/groups"
    archive: no
    recursive: yes
    delete: yes
    owner: yes
    group: yes
    rsync_opts: ["--chown={{ minecraft_user }}:{{ minecraft_group }}"]

- name: 'Tracks'
  <<: *rst
  synchronize:
    src: tracks/
    dest: "{{ perm_dir }}/tracks"
    archive: no
    recursive: yes
    delete: yes
    owner: yes
    group: yes
    rsync_opts: ["--chown={{ minecraft_user }}:{{ minecraft_group }}"]

- name: 'User permissions directory'
  file:
    <<: *mco
    path: "{{ perm_dir }}/users"
    state: directory

- name: 'User permissions'
  <<: *rst
  copy:
    <<: *mco
    dest: "{{ perm_dir }}/users/{{ item.uuid }}.yml"
    content: "{{ item | to_nice_yaml }}"
  loop: "{{ minecraft_users }}"

- name: 'Disallow syncing'
  lineinfile:
    path: /etc/sudoers
    state: absent
    line: "{{ lookup('env', 'USER') }} ALL=NOPASSWD: /usr/bin/rsync"
    validate: '/usr/sbin/visudo -cf %s'
