---
- name: 'Install Lighttpd'
  apt:
    name: lighttpd
- name: 'Allow http in'
  ufw:
    rule: allow
    port: http
- name: 'Allow https in'
  ufw:
    rule: allow
    port: https
- name: 'Lighttpd config'
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
  notify:
    - restart lighttpd
