---
time_zone: 'America/New_York'

minecraft_user: minecraft
minecraft_group: minecraft
minecraft_dir: /opt/minecraft
minecraft_ram: "{{ (ansible_memtotal_mb * 0.5) | round | int }}M"
minecraft_port: '25565'

user_whitelist: "{{ vault_user_whitelist | to_json }}"
# - name: username
#   uuid: 0ddba110-0000-0000-0000-ba53ball0000
# - name: anotheruser
#   uuid: facade22-0000-0000-0000-5caff01d0000

paper_version: '1.15.2'
paper_build: '121'

mcrcon_reinstall_from_source: no
mcrcon_version: '0.7.1'
rcon_port: 25575
rcon_password: "{{ vault_rcon_password }}"

bukkit_plugins:
  - name: Vault
    version: '1.7.2'
    file: vault.jar
    checksum: ce7fca7917a09a265f694d4d7145e144cdb0327e
  - name: Cenotaph
    version: '5.6'
    file: cenotaph.jar
    checksum: f42ad17e4c07b85ff7fa005aef59973713499ed3
  - name: EssentialsX
    version: '2.17.2'
    file: essentialsx.jar
    checksum: 02051464b5f86af38bba32991e8acd76b42b9330
