---
mcrcon_reinstall_from_source: no
mcrcon_version: '0.7.1'
paper_version: '1.15.2'
paper_build: '121'
rcon_port: 25575
rcon_password: "{{vault_rcon_password}}"
minecraft_user: minecraft
minecraft_group: minecraft
minecraft_ram: "{{ (ansible_memtotal_mb * 0.5) | round | int }}M"
minecraft_port: '25565'
