---
time_zone: 'America/New_York'
admin_email: 'werebus@gmail.com'

minecraft_user: minecraft
minecraft_group: minecraft
minecraft_dir: /opt/minecraft
plugin_dir: "{{ minecraft_dir }}/server/plugins"
minecraft_ram: "{{ (ansible_memtotal_mb * 0.5) | round | int }}M"
minecraft_port: '25565'
minecraft_map_webroot: "{{ plugin_dir }}/dynmap/web"

minecraft_users: "{{ vault_minecraft_users }}"

paper_version: '1.17.1'

mcrcon_reinstall_from_source: no
mcrcon_version: '0.7.2'
rcon_port: 25575
rcon_password: "{{ vault_rcon_password }}"

perm_dir: "{{ plugin_dir }}/LuckPerms/yaml-storage"

bukkit_plugins:
  - name: Vault
    version: '1.7.3'
    file: vault.jar
    checksum: e1e443a08d3280f9dbcb233a8c3a20d4c1286a6d
  - name: Cenotaph
    version: '5.6'
    file: cenotaph.jar
    checksum: f42ad17e4c07b85ff7fa005aef59973713499ed3
  - name: EssentialsX
    version: '2.20.1'
    file: essentialsx.jar
    checksum: e626f9f250470bcf2feffbc3740f738f9cee50ef
  - name: LuckPerms
    version: '5.4.128'
    file: luckperms.jar
    checksum: 3ab0a738fc242ec3a699d38382400e4bbfdfc872
  - name: DynMap
    version: '3.2.1'
    file: dynmap.jar
    checksum: 5f7d7a46c8d5804dc4e18684f291a1bdbc463601
