---
time_zone: 'America/New_York'
admin_email: 'werebus@gmail.com'

minecraft_user: minecraft
minecraft_group: minecraft
minecraft_dir: /opt/minecraft
plugin_dir: "{{ minecraft_dir }}/server/plugins"
minecraft_ram: "{{ (ansible_memtotal_mb * 0.5) | round | int }}M"
minecraft_port: '25565'
minecraft_map_webroot: "{{ plugin_dir }}/dynmap/web"

minecraft_users: "{{ vault_minecraft_users }}"

paper_version: '1.16.5'
paper_build: '576'

mcrcon_reinstall_from_source: no
mcrcon_version: '0.7.2'
rcon_port: 25575
rcon_password: "{{ vault_rcon_password }}"

perm_dir: "{{ plugin_dir }}/LuckPerms/yaml-storage"

bukkit_plugins:
  - name: Vault
    version: '1.7.2'
    file: vault.jar
    checksum: e1e443a08d3280f9dbcb233a8c3a20d4c1286a6d
  - name: Cenotaph
    version: '5.6'
    file: cenotaph.jar
    checksum: f42ad17e4c07b85ff7fa005aef59973713499ed3
  - name: EssentialsX
    version: '2.17.2'
    file: essentialsx.jar
    checksum: 02051464b5f86af38bba32991e8acd76b42b9330
  - name: LuckPerms
    version: '5.3.16'
    file: luckperms.jar
    checksum: 9b25c10c2029b8af4f823b9388d3effbf5847cf6
  - name: DynMap
    version: '3.1 GA'
    file: dynmap.jar
    checksum: 7741cd0b223d4bb3f4395e996c8ce8c7a6145212
