---
time_zone: 'America/New_York'
admin_email: 'werebus@gmail.com'

minecraft_user: minecraft
minecraft_group: minecraft
minecraft_dir: /opt/minecraft
plugin_dir: "{{ minecraft_dir }}/server/plugins"
minecraft_ram: "{{ (ansible_memtotal_mb * 0.5) | round | int }}M"
minecraft_port: '25565'
minecraft_map_webroot: "{{ plugin_dir }}/dynmap/web"

minecraft_users: "{{ vault_minecraft_users }}"
# - name: username
#   uuid: 0ddba110-0000-0000-0000-ba53ball0000
# - name: anotheruser
#   uuid: facade22-0000-0000-0000-5caff01d0000

paper_version: '1.15.2'
paper_build: '197'

mcrcon_reinstall_from_source: no
mcrcon_version: '0.7.1'
rcon_port: 25575
rcon_password: "{{ vault_rcon_password }}"

perm_dir: "{{ plugin_dir }}/LuckPerms/yaml-storage"

bukkit_plugins:
  - name: Vault
    version: '1.7.2'
    file: vault.jar
    checksum: ce7fca7917a09a265f694d4d7145e144cdb0327e
  - name: Cenotaph
    version: '5.6'
    file: cenotaph.jar
    checksum: f42ad17e4c07b85ff7fa005aef59973713499ed3
  - name: EssentialsX
    version: '2.17.2'
    file: essentialsx.jar
    checksum: 02051464b5f86af38bba32991e8acd76b42b9330
  - name: LuckPerms
    version: '5.0.88'
    file: luckperms.jar
    checksum: ae18a4dfd817b3dff1363674f9bda995a9ba2cda
  - name: DynMap
    version: '3.0-beta-10'
    file: dynmap.jar
    checksum: 5876da87f5d6cc2aa9659b7b7029e42bcd25d2df
