---
- name: 'Shared YML chunks'
  meta: noop
  args:
    minecraft_owned: &mco
      owner: "{{ minecraft_user }}"
      group: "{{ minecraft_group }}"

- name: 'Backups directory'
  file:
    <<: *mco
    path: "{{ minecraft_dir }}/backups"
    state: directory
- name: 'Backup script'
  template:
    <<: *mco
    src: backup.sh.j2
    dest: "{{ minecraft_dir }}/tools/backup.sh"
    mode: '755'
- name: 'Backup service'
  template:
    src: minecraft-backup.service.j2
    dest: /etc/systemd/system/minecraft-backup.service
- name: 'Backup timer'
  copy:
    src: files/minecraft-backup.timer
    dest: /etc/systemd/system/minecraft-backup.timer
- name: 'Enable backup timer'
  systemd:
    name: 'minecraft-backup.timer'
    enabled: yes
    state: started
    daemon_reload: yes

