version:
  version: '5.6'
  last_run_version: '5.6'

core:
  cenotaph_sign: 'true'
  save_cenotaph_list: 'true'
  void_check: 'true'
  one_block_up_check: 'true'
  explosion_protection: 'true'

  sign:
    line1: '{name}'
    line2: RIP
    line3: '{date}'
    line4: '{time}'

    date_format: MM/dd/yyyy
    time_format: hh:mm a

  disable_in_worlds:
  dynmap_enable: 'false'
  worldguard_enable: 'false'
  holographic_displays_enable: 'false'
  cenotaph_cost: '0.0'

removal:
  destroy_quick_loot: 'false'
  cenotaph_remove: 'false'
  remove_time: '3600'
  level_based_removal: 'false'
  level_based_time: '60'
  remove_when_empty: 'false'
  keep_until_empty: 'false'

security:
  security_enable: 'false'
  security_remove: 'true'
  security_time_out: '900'

startup:
  enable_ascii: 'false'
