deftemplatesuffix: hires

storage:
  type: filetree
 
components:
  - class: org.dynmap.ClientConfigurationComponent
  
  #- class: org.dynmap.InternalClientUpdateComponent
    #sendhealth: true
    #sendposition: true
    #allowwebchat: true
    #webchat-interval: 5
    #hidewebchatip: false
    #trustclientname: false
    #includehiddenplayers: false
    #use-name-colors: false
    #use-player-login-ip: true
    #require-player-login-ip: true
    #block-banned-player-chat: true
    #webchat-requires-login: false
    #webchat-permissions: true
    #chatlengthlimit: 256
    ## hideifshadow: 4
    ## hideifundercover: 14
    #hideifsneaking: false
    #protected-player-info: false
    #hide-if-invisiblity-potion: true
    #hidenames: false

  - class: org.dynmap.JsonFileClientUpdateComponent
    writeinterval: 1
    sendhealth: true
    sendposition: true
    allowwebchat: false
    # webchat-interval: 5
    # hidewebchatip: false
    includehiddenplayers: false
    use-name-colors: false
    use-player-login-ip: false
    require-player-login-ip: false
    block-banned-player-chat: true
    hideifshadow: 0
    hideifundercover: 0
    hideifsneaking: false
    # webchat-requires-login: false
    # webchat-permissions: false
    # chatlengthlimit: 256
    hide-if-invisiblity-potion: true
    hidenames: false

  # - class: org.dynmap.SimpleWebChatComponent
    # allowchat: false
    # allowurlname: false
  
  - class: org.dynmap.MarkersComponent
    type: markers
    showlabel: false
    enablesigns: false
    default-sign-set: markers
    showspawn: true
    spawnicon: world
    spawnlabel: "Spawn"
    showofflineplayers: false
    offlinelabel: "Offline"
    offlineicon: offlineuser
    offlinehidebydefault: true
    offlineminzoom: 0
    maxofflinetime: 30
    showspawnbeds: false
    spawnbedlabel: "Spawn Beds"
    spawnbedicon: bed
    spawnbedhidebydefault: true
    spawnbedminzoom: 0
    spawnbedformat: "%name%'s bed"
    showworldborder: true
    
  #- class: org.dynmap.ClientComponent
    #type: chat
    #allowurlname: false
  #- class: org.dynmap.ClientComponent
    #type: chatballoon
    #focuschatballoons: false
  #- class: org.dynmap.ClientComponent
    #type: chatbox
    #showplayerfaces: true
    #messagettl: 5
    ## scrollback: 100
    ## visiblelines: 10
    #sendbutton: false

  - class: org.dynmap.ClientComponent
    type: playermarkers
    showplayerfaces: true
    showplayerhealth: true
    showplayerbody: false
    smallplayerfaces: false
    hidebydefault: false
    layerprio: 0
    label: "Players"
    
  #- class: org.dynmap.ClientComponent
  #  type: digitalclock
  - class: org.dynmap.ClientComponent
    type: link

  - class: org.dynmap.ClientComponent
    type: timeofdayclock
    showdigitalclock: true
    showweather: true
  # Mouse pointer world coordinate display
  - class: org.dynmap.ClientComponent
    type: coord
    label: "Location"
    hidey: false
    show-mcr: false

display-whitelist: false
renderinterval: 2
renderacceleratethreshold: 60
renderaccelerateinterval: 0.2
tiles-rendered-at-once: 2
usenormalthreadpriority: false
saverestorepending: true
save-pending-period: 900
zoomoutperiod: 30
initial-zoomout-validate: true
tileupdatedelay: 30
enabletilehash: true
# hideores: true
# better-grass: true
smooth-lighting: true
use-brightness-table: true
block-id-alias:
#    "14": 1
#    "15": 1
#    "16": 1
image-format: png
use-generated-textures: true
correct-water-lighting: true
transparent-leaves: true
ctm-support: true
custom-colors-support: true
skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png"

render-triggers:
  #- playermove
  #- playerjoin
  - blockplaced
  - blockbreak
  - leavesdecay
  - blockburn
  - chunkgenerated
  - blockformed
  - blockfaded
  - blockspread
  - pistonmoved
  - explosion
  #- blockfromto
  #- blockphysics
  - structuregrow
  - blockgrow
  #- blockredstone

# webpage-title: "My Awesome Server Map"
tilespath: web/tiles
webpath: web
exportpath: export
webserver-port: 8123
max-sessions: 30
disable-webserver: true
allow-symlinks: true
login-enabled: false
login-required: false
timesliceinterval: 0.0
maxchunkspertick: 200
progressloginterval: 100
# parallelrendercnt: 4
updaterate: 2000
fullrenderplayerlimit: 5
updateplayerlimit: 0
per-tick-time-limit: 50
update-min-tps: 18.0
fullrender-min-tps: 18.0
zoomout-min-tps: 18.0

showplayerfacesinmenu: true
grayplayerswhenhidden: true

player-sort-permission-nodes:
  - bukkit.command.op
  
# http-response-headers:
#   Access-Control-Allow-Origin: "my-domain.com"
#   X-Custom-Header-Of-Mine: "MyHeaderValue"

trusted-proxies:
  - "127.0.0.1"
  - "0:0:0:0:0:0:0:1"
  
joinmessage: "%playername% joined"
quitmessage: "%playername% quit"
spammessage: "You may only chat once every %interval% seconds."
webmsgformat: "&color;2[WEB] %playername%: &color;f%message%"
showlayercontrol: true
check-banned-ips: true
defaultzoom: 0
defaultworld: world
defaultmap: flat
# followzoom: 3
# followmap: surface

persist-ids-by-ip: true
cyrillic-support: false
round-coordinates: true

msg:
  maptypes: "Map Types"
  players: "Players"
  chatrequireslogin: "Chat Requires Login"
  chatnotallowed: "You are not permitted to send chat messages"
  hiddennamejoin: "Player joined"
  hiddennamequit: "Player quit"

url:
  # configuration: "up/configuration"
  # update: "up/world/{world}/{timestamp}"
  # sendmessage: "up/sendmessage"
  # login: "up/login"
  # register: "up/register"
  # tiles: "tiles/"
  # markers: "tiles/"

custom-commands:
  image-updates:
    preupdatecommand: ""
    postupdatecommand: ""

snapshotcachesize: 500
soft-ref-cache: true
verbose: false

# debuggers:
#   - class: org.dynmap.debug.LogDebugger
dump-missing-blocks: false
